set(CMAKE_SYSTEM_NAME Generic) 
set(CMAKE_SYSTEM_PROCESSOR arm) 
 
set(TOOLCHAIN_PREFIX arm-none-eabi-) 

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc ) 
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER}) 
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy) 
set(CMAKE_SIZE ${TOOLCHAIN_PREFIX}size) 

#  Configure the executable suffix for assembly and C files.
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf") 
set(CMAKE_EXECUTABLE_SUFFIX_C ".elf") 
  
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY) 